# Generated by Django 3.1 on 2020-08-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0002_auto_20200811_1106'),
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='idGenero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genero.genero', verbose_name='Gênero'),
        ),
    ]
