# Generated by Django 3.1 on 2020-08-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
